server:
  port: 63000

dubbo:
  application:
    name:  dubbo-consumer
  registry:
    #address: zookeeper://192.168.8.240:2181 # zookeeper address ip
    address: zookeeper://192.168.8.240:2181?backup=192.168.8.240:2182,192.168.8.240:2183  # zookeeper cluster address ip
    timeout: 10000 # 解决 zookeeper not connected - https://blog.csdn.net/weixin_43275277/article/details/106544510
    protocol: zookeeper
    check: false
  # dubbo-admin配置
  metadata-report:
    address: zookeeper://192.168.8.240:2181?backup=192.168.8.240:2182,192.168.8.240:2183  # zookeeper cluster address ip
  monitor:
    protocol: register
  consumer:
    # 启动时检查服务提供者是否存在，不存在就报错
    check: false
    timeout: 3000